# Generated by Django 4.0.3 on 2022-03-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orderbook_ordered_orderbook_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_created_date',
            new_name='start_date',
        ),
    ]
